### ISSUE TITLE
GitHub still complaining about NodeJS 12

### ISSUE THREAD

**Issue by daenney** [haveyoudebuggedit/gotestfmt-action#11]
Despite #6 and a tag for v2.1.0 existing that includes that commit, I'm still seeing the following warning logged by actions:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: GoTestTools/gotestfmt-action@v2

I'm not entirely sure why, as my workflow is using `GoTestTools/gotestfmt-action@v2` so I would expect it to pick up `v2.1.0` and not complain.

**Comment by daenney** [comment]
Ah, though v2.1.0 exists, `v2` is a branch, which hasn't been updated with the recent set of commits. This means that to get the update currently, you have to explicitly use `GoTestTools/gotestfmt-action@v2.1.0`.

However, all the examples use `@v2`, so this currently doesn't quite behave as expected.

**Comment by ghost** [comment]
Thank you @daenney, I've opened a PR. Once approved, this issue should be resolved.

**Comment by engelmi** [comment]
Just approved and merged #12. Can you verify that the NodeJS 12 issue is resolved? @daenney

**Comment by daenney** [comment]
Weirdly enough I'm getting a `gotestfmt` not found now during my tests. It works fine on v2.1.0, but v2 seems broken now.

**Comment by daenney** [comment]
You can see the pipeline here: https://github.com/daenney/ssrf/actions/runs/3613638409/jobs/6089536371

**Comment by ghost** [comment]
Can you try switching the checkout and gotestfmt setup step?

**Comment by daenney** [comment]
That fixes it. Little surprising since it worked before and with v2.1.0 the other way around but I'll take it :smile:. I don't get any annotations with warnings about the NodeJS version anymore so that's fixed too.

**Comment by ghost** [comment]
@engelmi any clue why the checkout being after the gotestfmt setup breaks the call?

**Comment by engelmi** [comment]
In https://github.com/GoTestTools/gotestfmt-action/pull/10 the directory for extracting `gotestfmt` was changed to `GITHUB_WORKSPACE` (see [here](https://github.com/GoTestTools/gotestfmt-action/pull/10/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R29)) to enable windows runner. This directory is also used by the checkout action (see [documentation](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)) - and, when looking at the pipeline from @daenney, it apparently clears this directory
https://github.com/daenney/ssrf/actions/runs/3613638409/jobs/6089536371#step:4:22
I didn't know about this. Should we change it to `GITHUB_PATH`, for example? @janosdebugs

**Comment by ghost** [comment]
I think so, yes.
